### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by JaVo93** [HoloLabInc/MRTKExtensionForOculusQuest#1]
Hi,

first thank you for your great work. I installed the apk and it worked instantly. Unfortunately in Unity after importing Oculus Integration, MRTK Foundation and Examples and open the example OculusMRTK scene I get this NullReferenceException:

NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.Input.MixedRealityControllerMapping.SynchronizeInputActions (Microsoft.MixedReality.Toolkit.Input.MixedRealityInteractionMapping[] otherControllerMapping) (at Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMapping.cs:205)
Microsoft.MixedReality.Toolkit.Input.MixedRealityControllerMappingProfile.AddMappings () (at Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs:162)
Microsoft.MixedReality.Toolkit.Input.MixedRealityControllerMappingProfile.Awake () (at Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs:129)

Do you have any idea to solve this exception?

**Comment by mr0ng** [comment]
Same here

**Comment by trober** [comment]
Same issue with:
Unity 2018.4.14f1, MRTK 2.2 Foundation & Examples imported, Windows 10 machine, Oculus Integrations 12, Android project that builds for Quest

**Comment by andreibosco** [comment]
Same issue here:
- Unity 2019.2.17f1
- Oculus Integration 12
- MRTK 2.2 (imported all unitypackages except UnityAR)
- Brand new project with build settings set to Android

**Comment by tarukosu** [comment]
This issue is fixed at version v1.1.0.
