### ISSUE TITLE
Assets\MixedRealityToolkit.ThirdParty\OculusQuestInput\Scirpts\OculusQuestHandInputManager.cs(132,31): error CS0103: The name 'InputSystem' does not exist in the current context

### ISSUE THREAD

**Issue by kknsy** [HoloLabInc/MRTKExtensionForOculusQuest#6]
![image](https://user-images.githubusercontent.com/26211860/81651609-60829600-9465-11ea-9421-80496d07c338.png)
How can I solve this error？

**Comment by tarukosu** [comment]
I'm sorry but this repository is not maintained anymore.
Could you try this repository?

https://github.com/provencher/MRTK-Quest

**Comment by kknsy** [comment]
Is the reason for the latest version of vrtk，Thank you
